### ISSUE TITLE
Sponge API 8/9/10 support

### ISSUE THREAD

**Issue by CC-3301** [SkinsRestorer/SkinsRestorerX#1086]
Very good plugin, I started to use from Minecraft 1.7.10 version until now, I currently switched to SpongeForge 1.16.5 server, but I found that the plugin is only updated to API7, I hope the developer has time to update to API8

**Comment by xknat** [comment]
i know we did some work in https://github.com/SkinsRestorer/SkinsRestorerX/pull/809 (but closed it)
i don't recall what our judgment was on this

**Comment by mosemister** [comment]
~~I looked into this myself. In the current state of the sponge edition of Skin Restore it does not work due to many libraries used in skin restore are the same as the ones in sponge, however Skin Restore shades these libraries. So when sponge passes a Audience, the IDE says they are the same allowing it to compile, but thats pre-shading, so in reality it crashes with a NoSuchMethod.~~

~~With that being said, if you disable shading for sponge (and all common libraries) then the compiled jar is actually one that works with sponge vanilla (not tried forge, it wasnt supported in previous so i doubt it will work)~~

Somehow I cloned a git version 3 weeks prior (aka not having https://github.com/SkinsRestorer/SkinsRestorerX/commit/edaeb383ecbe07d1a18bd0018f2b8754e2a4a63c ) Sorry for the miss information, ill double check that later.

With that being said, there are still issues with the sponge version on the current such as "Incorrect argument for command" when using the commands it suggests and a crash on bootup 

```shell
Could not pass StartingEngineEvent$Impl to skinsrestorer
java.lang.NoSuchMethodError: 'java.lang.String net.skinsrestorer.shared.subjects.messages.SkinsRestorerLocale.getMessage(net.skinsrestorer.shared.subjects.SRForeign, net.skinsrestorer.shared.subjects.messages.Message, net.kyori.adventure.text.minimessage.tag.resolver.TagResolver[])'
```

**Comment by AlexProgrammerDE** [comment]
We've talked about this internally and decided that it is too much effort to support multiple versions of the Sponge API in the long term. (There's almost a new major bump on every new mc release)
Thus we've decided it'll be best to only support the version the sponge documentation is written for. (Currently 8.0.0) and only support a newer sponge version once their documentation is written for that new version.
7.0.0 support will end with the release of v15 and starting v15 we'll support only 8.0.0 instead.

**Comment by mosemister** [comment]
To be fair, api wise its not that different between 8-11 (currently).

As the documentation writer for sponge i can tell you that api 10 docs will start as soon as we are comfortable with api 8s docs (we are pulling a microsoft and Apple and are skipping 9)

**Comment by AlexProgrammerDE** [comment]
We'll start migrating to API 10 once the documentation is out to the public and replaces 8.0.0 as the default. For us writing duplicate code for 3+ sponge versions is nothing we're willing to do. We've already got a lot of technical debt by writing mappings for every mc version since 1.18+. And that's only for the few nms we're actually accessing. Writing duplicate code for a different base API even with slight changes would only slow down our development, as a sponge API bugfix would require changing one thing in 3+ places (or triple more in 2-4 years).
