### ISSUE TITLE
Make auto updates opt-in instead of opt-out

### ISSUE THREAD

**Issue by radiant-ai** [SkinsRestorer/SkinsRestorerX#1384]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

Please make plugin to have disabled auto updates by default. This is a real big pain which authors add to their plugins.

When you have a ton of different servers it is difficult to watch out for breaking changes when plugins update. Especially when you use docker for servers.

E.g. what happened not only to me but to some different server administrates:
- SkinsRestorer updated itself
- Plugins which depended on SkinsRestorer got broken
- Now if you try to rollback SkinsRestorer the new config is not compatible with older version
- You have a server with either busted skins or other dependencies

**Comment by xknat** [comment]
Hey there,
> This is a real big pain which authors add to their plugins.

We understand your frustration that this update may have come sudden. We have been working on this update for over a year and did have a transition window for half a year to migrate to v15. Maybe you have missed our message? please let us know so we know to improve our ways of communicating.

> SkinsRestorer updated itself

Our policy is to always use the latest release of the plugin. We feel that this is necessary to fix bugs and reduce troubleshooting issues from older versions. We only provide support for the latest release, therefor we rely on testers to test our new dev builds. in the future we will add a way to opt in on dev builds so we hope to reduce issues like these more early on.

> Plugins which depended on SkinsRestorer got broken

We informed some listed / known plugins that use to update ahead of time.

> Now if you try to rollback SkinsRestorer the new config is not compatible with older version

We do not support older versions of skinsrestorer.

> You have a server with either busted skins or other dependencies

Since 14.1.10 (Dec 10, 2021)  we have been a fairly "stable" plugin with little breaking changes.
Now we we have taken the time (a whole year) to release everything we have planned at once.
Our goal was to prepare SkinsRestorer for another 3 - 5 years of development.

This has resulted in everything that has been build on v14 to break.
Still, we wanted everyone to migrate to this new version with the auto updater so our website, wiki, docs, info is all in sync.

Hope this helped, if you have more questions, feel free to drop by on our Discord.
Sorry for grammer, i am not the best writer with dyslexia
