### ISSUE TITLE
/skins (gui) for bungeecord

### ISSUE THREAD

**Issue by McLive** [SkinsRestorer/SkinsRestorerX#154]

**Comment by xknat** [comment]
![image](https://user-images.githubusercontent.com/10220139/65447100-2319bb80-de36-11e9-8c06-29882e0b8a89.png)
This is a hot item now, we are getting more and more request for this as no plugin is currently able to do this, It might be hard to pull this off due to the limited api between bungee cord & spigot,
Mysql might be a MUST HAVE for this feature start with.
