### ISSUE TITLE
geyser (floodgate) & bungee still dont work to well.

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#323]
- [ ] add floodgate support for bungee
- [ ] apply player name skin with \\w regex filter.
- [ ] see what char might not be allowed by mysql

**Comment by Grizzly90** [comment]
I will leave a few points that make troubles atm.

- Floodgate needs a non-alphanumeric prefix, so no duplicate usernames can occur
______________
the following parts occur after changing the regex for valid usernames to `^\*?[a-zA-Z0-9_]{3,16}$` and using asterix as prefix
- `/skin clear` throws a message, that this isn't a premium player and that the UUID will be retrived from Mojang API (Floodgate uses a different UUID: [How to whitelist floodgate players](https://github.com/GeyserMC/Geyser/wiki/FAQ#how-do-i-add-players-to-the-whitelist-when-using-floodgate)
- The chosen Skin won't be selected/activated on a new login
- on login also the message that the plugin tries to `[SkinsRestorer] Trying Mojang API to get UUID for player Grizzly907732.`
- sometimes getten a skin via URL won't work: `[SkinsRestorer] [ERROR] MS:could not generate skin url: https://www.minecraftskins.com/uploads/skins/2020/09/25/c-h-i-l-l-15350239.png?v264` Maybe because of their DDOS protection?

**Comment by xknat** [comment]
I first want it to have "not break".
After that i can into looking to check on floodgate/xbox uuid side.
ty for testing out. make sure to enable debug when doing so ;)

**Comment by xknat** [comment]
Did post a hotfix (see above)
More work needs to be done to find the exact places on which the filters needs to be added.
It might also be on best intrest to not filter all \w chars because other country's like china might use them.
Doing this on getDefaultSkinNameIfEnabled might not be the best place to filter the name....

**Comment by Grizzly90** [comment]
I will test it as soon as possible.

Maybe you can check if floodgate is loaded and test if the Player a bedrock player via floodgate API? (we have choosed that way to handle players different if they are bedrock players) so you will know that the Name was already validated by floodgate.
I can try to add this to a fork and PR if you want to.

**Comment by xknat** [comment]
We don't use uuid to handle players. Only for skins we need em

**Comment by Grizzly90** [comment]
After test.
Floodgate player can join but doesn't can change skin.
Java player can change their Skin.

**Comment by TOWUK** [comment]
nice, i am use floodgate on velocity :)

**Comment by xknat** [comment]
@TOWUK ^

**Comment by Grizzly90** [comment]
On rejoin the previous chosen skin won't be applied. So I changed the replacement of the * for bedrockplayers form "·" to ".". Now the chosen skin can be applied on join.

**Comment by Grizzly90** [comment]
commit: https://github.com/SkinsRestorer/SkinsRestorerX/commit/f43c3ae3d2f77da12ffd1dcb3dc2ec252571d534 and the Previous cause, that the getPlayerSkin() is called without * in front. but they are stored with * in front so the player won't be found in storage. if he has a non-Word-Prefix. Don't know what this change is needed for.

**Comment by xknat** [comment]
> but they are stored with * in front

consider checking skin storage
